name: Action Secrets

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: |
          echo "My top secret: ${{ secrets.MY_TOP_SECRET }}"
          echo "I dont extst: ${{ secrets.i_dont_exist }}"

      - name: Print secret as an environemnt variable
        run: |
          echo "MY_TOP_SECRET: $MY_TOP_SECRET"
        env:
          AZURE_CREDENTIALS: ${{ secrets.MY_TOP_SECRET }}
