name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  build-api:
    needs: build-app
    runs-on: macos-latest
    steps:
      - name: Run a dependency workflow
        run: |
          echo Hello Shruthi,
          echo Welcome to githubactions workflow.

  build:
    runs-on: ubuntu-latest
    steps:
      - name: This is a build job
        run: echo This is a build job

  package:
    needs: ["build-app", "build-api"]
    runs-on: windows-latest
    steps:
      - name: This is a package job
        run: echo This is a package job
