name: Continuous Integration

on:
  workflow_dispatch:

jobs:
  job-title:
    runs-on: ubuntu-latest
    steps:
      - name: Set Custom variable
        run: |
          echo "action_state=red" >> $GITHUB_ENV

      - name: Display custom variable
        run: echo "$action_state"
