name: CI

on:
  workflow_dispatch:

jobs:
  job-title:
    runs-on: ubuntu-latest
    steps:
      - name: This is the first custom variable workflow
        run: |
          echo "action_state=red" >> $GITHUB_ENV
          echo $action_state
