name: Sync Bucket
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install AWS CLI
        run: sudo apt-get install awscli

      - name: Upload index.html to S3 bucket
        run: aws s3 cp index.html s3://${{ secrets.AWS_S3_BUCKET }}/index.html --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
